volumes:
  pgdata:
  built_frontend:

services:
  frontend:
    image: cocancerscope-frontend
    build: ./frontend
    command: yarn build
    volumes:
      - built_frontend:/app/build
    environment:
      - "VITE_API=https://co-cancer-scope.cu-dbmi.dev/api"

  nginx:
    image: nginx:1.19.6-alpine
    ports:
      - "80:80"
    volumes:
      - ./services/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - built_frontend:/usr/share/nginx/html
    depends_on:
      - backend
