name: Add a new data resource
description: Suggest a data resource
title: "[New Data] <title>"
labels: ["Feature Request", "Needs Triage", "New Data"]
body:
- type: input
  attributes:
    label: Name
    description: A brief title/name for the new data resource. 
  validations:
    required: true
- type: input
  attributes:
    label: URL
    description: The URL for accessing the data resource
  validations:
    required: true
- type: textarea
  attributes:
    label: Description
    description: A description, potentially cut-and-pasted from the data provider or website.
  validations:
    required: True
- type: textarea
  attributes:
    label: Relevance
    description: |
      Provide a brief description of the relevance to the Cancer Center and its COE mission.
      Examples might include:

      1. Adding these data will ...
      1. Project XYZ is a COE priority and ...
      1. These data help describe the catchment because ...
    render: markdown
  validations:
    required: true
- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about your request!

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
